package com.alienation.game;

/**
 * Items that can't be added to inventory
 */
//TODO: LOSE THE EUNUM MAKE A LIST
public enum Xitems {LOCKERS, LOCKER, PODS, CABINET, COMPUTERS, COMPUTER, DESK, SOFA, RACKS, CAGE, SUPPLIES, REFRIGERATOR, MICROWAVE, CABINETS, DUSTBIN, MONITOR, CONTROL_PANEL, PILOT_SEATS, ALIEN, BED, MIRROR, OLD_BOX}

